version: "3.8"

services:
  revocation_redis:
    container_name: revocation_redis
    build:
      context: docker
      dockerfile: redis.Dockerfile
    networks:
      - redis_network
    ports:
      - 6378:6379
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
      - /tmp/revocation_redis_data:/data
  refresh_redis:
    container_name: refresh_redis
    build:
      context: docker
      dockerfile: redis.Dockerfile
    networks:
      - redis_network
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
      - /tmp/refresh_redis_data:/data
  user_mongodb:
    image: mongo:latest
    container_name: user_mongodb
    networks:
      - redis_network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: authix
      MONGO_INITDB_ROOT_PASSWORD: test123
    volumes:
      - /tmp/authix_mongo_db:/data/db
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
      - "9093:9093"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_LOG_RETENTION_HOURS=-1
      - KAFKA_CFG_LOG_RETENTION_BYTES=-1
    depends_on:
      - zookeeper
  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  redis_network:
