name: Docker Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: docker login
        uses: azure/docker-login@v1
        with:
          login-server: registry.nymann.dev
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build the Docker image
        run: make docker-build
